#!/bin/bash

if [[ $1 != "debug" ]] && [[ $1 != "release" ]]; then
	echo "Please choose either debug or release modes please..."
	exit 1
fi

mkdir -p build/$1

cd build/$1

qmake "CONFIG+=${1}" ../../icu_devices.pro

make
