#!/bin/bash

BLUE='\033[0;36m'
GREEN='\033[1;32m'
NC='\033[0m'

IP_RASP1='10.42.0.67'
IP_RASP2='10.42.0.46'
RASP1='pi@'${IP_RASP1}
RASP2='pi@'${IP_RASP2}

printf "\n${GREEN}================================================================================\n"
printf "Detaching all hardwares in mocked ICU room\n"
printf "================================================================================${NC}\n"

printf "${BLUE}Running commands in localmachine ${NC}\n"

printf "${BLUE}Detach all devices ${NC}\n"
sudo /usr/lib/linux-tools/4.15.0-135-generic/usbip detach -p 00

printf "${BLUE}Running commands in Raspberry pi ${IP_RASP1} and ${IP_RASP2} ${NC}\n"
scp -i ~/.ssh/id_rsa cancel_remote ${RASP1}:/home/pi/
ssh -i ~/.ssh/id_rsa ${RASP1} './cancel_remote'
scp -i ~/.ssh/id_rsa cancel_remote ${RASP2}:/home/pi/
ssh -i ~/.ssh/id_rsa ${RASP2} './cancel_remote'

printf "\n${GREEN}================================================================================\n"
printf "Detached all hardwares in mocked ICU room\n"
printf "================================================================================${NC}\n\n"
